### ISSUE TITLE
Retrieve metadata such as alt text

### ISSUE THREAD

**Issue by ericmasiello** [Chuloo/gatsby-source-cloudinary#16]
Is it possible through the existing plugin to retrieve alt text specified in Cloudinary? Using GraphiQL, I did not see anything that resembled this data.

Thanks in advance!

**Comment by Chuloo** [comment]
hi @ericmasiello you can do this by adding a `context: true` option in the gatsby-config options. Once this is done, any custom metadata or context data you add to the image on Cloudinary will be available in the `context` data field. Using the GraphiQL explorer, this is a sample query for all images:

```
query CloudinaryImage {
  allCloudinaryMedia {
    edges {
      node {
        context {
          custom {
            alt
          }
        }
        secure_url
        url
        public_id
      }
    }
  }
}

``` 

the node field with a context will return data like this, while other fields without context will return `null` for the context data:

```
{
          "node": {
            "context": {
              "custom": {
                "alt": "man-on-street"
              }
            },
            "secure_url": "https://res.cloudinary.com/chuloo/image/upload/q_auto,f_auto/v1580395766/gatsby-source-cloudinary/12.jpg",
            "url": "http://res.cloudinary.com/chuloo/image/upload/q_auto,f_auto/v1580395766/gatsby-source-cloudinary/12.jpg",
            "public_id": "gatsby-source-cloudinary/12"
          }
        }
```

**Comment by ericmasiello** [comment]
Thanks. I saw you updated the docs. 👍
