### ISSUE TITLE
The `tags` option doesn't seem to work

### ISSUE THREAD

**Issue by thomasmost** [Chuloo/gatsby-source-cloudinary#17]
The only thing I get back on a node is the `secure_url`

Gatsby config

```
    {
      resolve: `gatsby-source-cloudinary`,
      options: {
        cloudName: process.env.CLOUDINARY_CLOUD_NAME,
        apiKey: process.env.CLOUDINARY_API_KEY,
        apiSecret: process.env.CLOUDINARY_API_SECRET,
        resourceType: `image`,
        prefix: `my-cloudinary-folder/`,
        tags: true,
      },
    },
    ...
  ],
```

**Comment by Chuloo** [comment]
Hi, you must have specified the tags for the image in your Cloudinary account. Here's a sample Graphql response I get for an image on my account which has tags.

![image](https://user-images.githubusercontent.com/22301208/83082128-95acfc00-a093-11ea-8825-7277f399224f.png)

**Comment by Chuloo** [comment]
Closing this out for now. Please leave a comment if this is still an issue.
