### ISSUE TITLE
Responsive images question

### ISSUE THREAD

**Issue by gavb17** [Chuloo/gatsby-source-cloudinary#18]
Hi
Is there a way to source image sizes based on the viewpoint size? 
The demo site and from the investigation I have been doing, the largest image size is downloaded.

Can see via **gatsby-transformer-cloudinary** this is possible but the images need to be uploaded via the default Gatsby interface to create the File nodes, which does not seem to allow for bulk upload and is why I was hoping to use Cloudinary for handling images.

Any thoughts on this would be great, thinking I am missing something.

Gavin

**Comment by Chuloo** [comment]
Hi, with gatsby-transformer-cloudinary, you can upload images in bulk from a source folder to Cloudinary and use them on your website. These Images will be used with gatsby-image. With gatsby-image you can fetch either a fluid image that takes the full width of the parent container or you can get a fixed image with static width. Here's a tutorial I wrote on how this works.
https://scotch.io/tutorials/serving-remote-optimized-images-w-gatsby-image

With gatsby and Cloudinary, you can specify the width of the Image you want either using the plugin or as a Cloudinary transformation.

Also, gatsby-transformer-cloudinary has `getFluidImageObject` and `getFixedImageObject` with which you can source an Image directly from Cloudinary into gatsby-image without having graphql queries. I wrote about this here:
https://scotch.io/tutorials/serving-remote-optimized-images-w-gatsby-image-wo-graphql

Let me know if this solves your issue or not :)

**Comment by Chuloo** [comment]
Closing this one out. Please feel free to re-open an issue if there are further questions
