### ISSUE TITLE
Question on use with blogs

### ISSUE THREAD

**Issue by stephencweiss** [Chuloo/gatsby-source-cloudinary#19]
👋 Hi! This looks like a great plugin -- was just thinking about use cases and it doesn't seem appropriate for a markdown blog given that the images are sourced via a graphql query and the blog would not have access to that (unless it's written in MDX?).

Cheers!

**Comment by Chuloo** [comment]
Hi, yes you need to make graphql queries to fetch images using this plugin. MDX is really cool too because of the experience gotten from writing interactive components in markdown.
