### ISSUE TITLE
The gatsby-source-cloudinary plugin has generated no Gatsby nodes. Do you need it? 

### ISSUE THREAD

**Issue by Wookie93** [Chuloo/gatsby-source-cloudinary#20]
Hello,
I try to create images gallery in my gatsby project. I decided to use cloudinary, however it do not want to work. I used Static Query the component. I uploaded photos on the Cloudinary 
How can I fix it?

**Steps to reproduce**

 Follow instructions from https://scotch.io/tutorials/handling-images-in-gatsby-with-high-performance

- Install gatsby-source-cloudinary
- Setup your environments
- Run local server

**Expected result**
My local server will run and I will see images from cloudinary on my page.

**Actual result**

I get errors:

- The gatsby-source-cloudinary plugin has generated no Gatsby nodes. Do you need it?
- Cannot query field "allCloudinaryMedia" on type "Query".

**Comment by Chuloo** [comment]
Hi, can you share what the `gatsby-source-cloudinary` portion of your gatsby-config.js file looked like? it should specify the Cloudinary folder you would like to pull images from, and that folder should contain images.

**Comment by Wookie93** [comment]
Hi, 
Ok, I found a problem. I made two typo mistakes. Sorry.
