### ISSUE TITLE
Only returns up to 500 results.

### ISSUE THREAD

**Issue by tylermenezes** [Chuloo/gatsby-source-cloudinary#5]
This is documented, but it seems like support for repositories with over 500 files should be possible.

If no one else solves this by the time I encounter this issue I will happily submit the PR.

**Comment by tobob** [comment]
if someone wants to increase his limit to 1000 he can use my version, probably I will make it limitless in this week and I will make PR

(but remember to set `maxResult` to 500)

**Comment by coderkind** [comment]
How do you call `x` number of results? The default seems to be set to 10 (and I can't increase this).

**Comment by Chuloo** [comment]
Hi @coderkind did you try setting `maxResults` in the plugin options to say 500?

**Comment by coderkind** [comment]
@Chuloo thanks a lot; that sorted it.
